

#ifndef COMMAND_NAME_DEFAULTS
#define COMMAND_NAME_DEFAULTS


#define END_SONG_CMD "ends"
#define PLAY_PHRASE_CMD "phrs"
#define GOTO_CMD "goto"
#define LOOP_CMD "loop"


#define END_CMD "END"
#define RETURN_CMD "RETURN"
#define SET_DURATION_CMD "SET_DUR"
#define SET_DURATION_SUS_AND_VEL_CMD "SET_D_SV"
#define SET_SUS_AND_VEL_CMD "SET_SV"
#define PLAY_NOTE_CMD "PLAY_NOTE"
#define REST_CMD "REST_NOTE"
#define TIE_CMD "TIE_NOTE"
#define PLAY_PERCUSSION_SOUND_CMD "PLAY_PERC"

#define SET_INSTRUMENT_CMD "SET_INSTR"
#define PAN_VALUE_CMD "SET_PAN"
#define PAN_FADE_CMD "FADE_PAN"
#define VIBRATO_CMD "SET_VIBRA"
#define DISABLE_VIBRATO_CMD "VIBRA_OFF"
#define MASTER_VOLUME_CMD "SET_MVOL"
#define MASTER_VOLUME_FADE_CMD "FADE_MVOL"
#define TEMPO_CMD "SET_TEMPO"
#define TEMPO_FADE_CMD "FADE_TEMPO"
#define TRANSPOSE_GLOBAL_CMD "GLOB_TRNSP"
#define TRANSPOSE_VOICE_CMD "VOC_TRNSP"
#define TREMOLO_CMD "SET_TREMO"
#define DISABLE_TREMOLO_CMD "TREMO_OFF"
#define VOICE_VOLUME_CMD "SET_VVOL"
#define VOICE_VOLUME_FADE_CMD "FADE_VVOL"
#define CALL_ROUTINE_CMD "CALL"
#define VIBRATO_FADE_CMD "FADE_VIBRA"
#define POST_PITCH_BEND_CMD "POST_BEND"
#define PRE_PITCH_BEND_CMD "PRE_BEND"
#define DISABLE_PITCH_BEND_CMD "BEND_OFF"
#define TUNE_CMD "TUNE"
#define ECHO_ENABLE_AND_VOLUME_CMD "SET_ECHO"
#define DISABLE_ECHO_CMD "ECHO_OFF"
#define ECHO_PARAMETERS_CMD "ECHO_PRMS"
#define ECHO_VOLUME_FADE_CMD "FADE_ECHO"
#define PITCH_SLIDE_CMD "SLIDE_IMM"
#define PERCUSSION_TABLE_CMD "SET_PBASE"





#define NOTE_COMMAND_BASE 0x01
#define PARAMETER_COMMAND_BASE 0xe0
#define PHRASE_COMMAND_BASE 0xfb

// 4 items
constexpr const char* PHRASE_COMMANDS[] = {
	END_SONG_CMD,
	PLAY_PHRASE_CMD,
	LOOP_CMD,
	GOTO_CMD
};

// 9 items?
constexpr const char* VOICE_COMMANDS[] = {
	END_CMD,
	RETURN_CMD,
	SET_DURATION_CMD,
	SET_DURATION_SUS_AND_VEL_CMD,
	SET_SUS_AND_VEL_CMD,
	PLAY_NOTE_CMD,
	REST_CMD,
	TIE_CMD,
	PLAY_PERCUSSION_SOUND_CMD
};

// 27 commands?
constexpr const char* NSPC_COMMANDS[] = {
	SET_INSTRUMENT_CMD,
	PAN_VALUE_CMD,
	PAN_FADE_CMD,
	VIBRATO_CMD,
	DISABLE_VIBRATO_CMD,
	MASTER_VOLUME_CMD,
	MASTER_VOLUME_FADE_CMD,
	TEMPO_CMD,
	TEMPO_FADE_CMD,
	TRANSPOSE_GLOBAL_CMD,
	TRANSPOSE_VOICE_CMD,
	TREMOLO_CMD,
	DISABLE_TREMOLO_CMD,
	VOICE_VOLUME_CMD,
	VOICE_VOLUME_FADE_CMD,
	CALL_ROUTINE_CMD,
	VIBRATO_FADE_CMD,
	POST_PITCH_BEND_CMD,
	PRE_PITCH_BEND_CMD,
	DISABLE_PITCH_BEND_CMD,
	TUNE_CMD,
	ECHO_ENABLE_AND_VOLUME_CMD,
	DISABLE_ECHO_CMD,
	ECHO_PARAMETERS_CMD,
	ECHO_VOLUME_FADE_CMD,
	PITCH_SLIDE_CMD,
	PERCUSSION_TABLE_CMD
};

/*
constexpr const char* COMMAND_NAMES[] = {
	PLAY_PHRASE_CMD,
	GOTO_CMD,
	LOOP_CMD,
	END_SONG_CMD,

	END_CMD,
	RETURN_CMD,
	SET_DURATION_CMD,
	SET_DURATION_SUS_AND_VEL_CMD,
	SET_SUS_AND_VEL_CMD,
	PLAY_NOTE_CMD,
	REST_CMD,
	TIE_CMD,
	PLAY_PERCUSSION_SOUND_CMD,


	SET_INSTRUMENT_CMD,
	PAN_VALUE_CMD,
	PAN_FADE_CMD,
	VIBRATO_CMD,
	DISABLE_VIBRATO_CMD,
	MASTER_VOLUME_CMD,
	MASTER_VOLUME_FADE_CMD,
	TEMPO_CMD,
	TEMPO_FADE_CMD,
	TRANSPOSE_GLOBAL_CMD,
	TRANSPOSE_VOICE_CMD,
	TREMOLO_CMD,
	DISABLE_TREMOLO_CMD,
	VOICE_VOLUME_CMD,
	VOICE_VOLUME_FADE_CMD,
	CALL_ROUTINE_CMD,
	VIBRATO_FADE_CMD,
	POST_PITCH_BEND_CMD,
	PRE_PITCH_BEND_CMD,
	DISABLE_PITCH_BEND_CMD,
	TUNE_CMD,
	ECHO_ENABLE_AND_VOLUME_CMD,
	DISABLE_ECHO_CMD,
	ECHO_PARAMETERS_CMD,
	ECHO_VOLUME_FADE_CMD,
	PITCH_SLIDE_CMD,
	PERCUSSION_TABLE_CMD
};
*/

constexpr int NSPC_CMD_ARGS[] = { 1, 1, 2, 3, 0, 1, 2, 1, 2, 1, 1, 3, 0, 1, 2, 3, 1, 3, 3, 0, 1, 3, 0, 3, 3, 3, 1 };











#endif




#ifndef LITERALS_DEFAULTS
#define LITERALS_DEFAULTS

#define COMMENT_LIT ";"
#define POINTER_LIT "$"
#define OBJECT_LIT "."
#define TABLE_LIT "dw"
#define VARIABLE_LIT "="
#define REFERENCE_LIT ":"
#define HEX_LIT "x"
#define BIN_LIT "%"
#define DEC_LIT "#"
#define NOTE_LIT ">"
#define PTR_OFFSET_LIT "[]"

#define NULL_LIT "NULL"

#define SEPARATOR_LIT ","

#endif


#ifndef LITERAL_TYPES
#define LITERAL_TYPES

#define TYPE_COMMENT 0
#define TYPE_POINTER 1
#define TYPE_OBJECT 2
#define TYPE_TABLE 3
#define TYPE_VARIABLE 4
#define TYPE_REFERENCE 5
#define TYPE_HEX 6
#define TYPE_BIN 7
#define TYPE_DEC 8
#define TYPE_NOTE 9
#define TYPE_NULL 10
#define TYPE_COMMAND 11


constexpr const char* TYPE_LITERALS[11] = {
	COMMENT_LIT,
	POINTER_LIT,
	OBJECT_LIT,
	TABLE_LIT,
	VARIABLE_LIT,
	REFERENCE_LIT,
	HEX_LIT,
	BIN_LIT,
	DEC_LIT,
	NOTE_LIT,
	NULL_LIT

};

#define NUM_TYPES 11

#endif



#ifndef SHOW_LINE_NUMBERS
#define SHOW_LINE_NUMBERS false
#endif


#ifndef FILEEXTENSIONS
#define FILEEXTENSIONS
#define unassembled_extension ".ssf"
#define assembled_extension ".sng"

#endif


#ifndef PATCH_INSTRUCTIONS_TAGS
#define PATCH_INSTRUCTIONS_TAGS
#define no_reassembly "#"
#define compression_tag "*"

#endif





